-- https://hack64.net/wiki/doku.php?id=super_mario_64:geometry_layout_commands

-- sky background params
BACKGROUND_OCEAN_SKY = 0
BACKGROUND_FLAMING_SKY = 1
BACKGROUND_UNDERWATER_CITY = 2
BACKGROUND_BELOW_CLOUDS = 3
BACKGROUND_SNOW_MOUNTAINS = 4
BACKGROUND_DESERT = 5
BACKGROUND_HAUNTED = 6
BACKGROUND_GREEN_SKY = 7
BACKGROUND_ABOVE_CLOUDS = 8
BACKGROUND_PURPLE_SKY = 9

-- geo layout macros

local function wrap(CC)
	return function(...)
		return {type=CC, ...}
	end
end
GEO_BRANCH_AND_LINK = wrap(0x00)
GEO_END = wrap(0x01)
GEO_BRANCH = wrap(0x02)
GEO_RETURN = wrap(0x03)
GEO_OPEN_NODE = wrap(0x04)
GEO_CLOSE_NODE = wrap(0x05)
GEO_ASSIGN_AS_VIEW = wrap(0x06)
GEO_UPDATE_NODE_FLAGS = wrap(0x07)
GEO_NODE_SCREEN_AREA = wrap(0x08)
GEO_NODE_ORTHO = wrap(0x09)
GEO_CAMERA_FRUSTUM = wrap(0x0A)
GEO_CAMERA_FRUSTUM_WITH_FUNC = GEO_CAMERA_FRUSTUM
GEO_NODE_START = wrap(0x0B)
GEO_ZBUFFER = wrap(0x0C)
GEO_RENDER_RANGE = wrap(0x0D)
GEO_SWITCH_CASE = wrap(0x0E)
GEO_CAMERA = wrap(0x0F)
GEO_TRANSLATE_ROTATE = wrap(0x10)
GEO_TRANSLATE_ROTATE_WITH_DL = GEO_TRANSLATE_ROTATE
GEO_TRANSLATE = GEO_TRANSLATE_ROTATE
GEO_TRANSLATE_WITH_DL = GEO_TRANSLATE_ROTATE
GEO_ROTATE = function(layer, rx, ry, rz, displayList)
	return GEO_TRANSLATE_ROTATE(layer, nil, nil, nil, rx, ry, rz, displayList)
end
GEO_ROTATE_WITH_DL = GEO_ROTATE
GEO_ROTATE_Y = function(layer, ry, displayList)
	return GEO_TRANSLATE_ROTATE(layer, nil, nil, nil, nil, ry, nil, displayList)
end
GEO_ROTATE_Y_WITH_DL = GEO_ROTATE_Y
GEO_TRANSLATE_NODE = wrap(0x11)
GEO_TRANSLATE_NODE_WITH_DL = GEO_TRANSLATE_NODE
GEO_ROTATION_NODE = wrap(0x12)
GEO_ROTATION_NODE_WITH_DL = GEO_ROTATION_NODE
GEO_ANIMATED_PART = wrap(0x13)
GEO_BILLBOARD_WITH_PARAMS = wrap(0x14)
GEO_BILLBOARD_WITH_PARAMS_AND_DL = GEO_BILLBOARD_WITH_PARAMS
GEO_BILLBOARD = function()
	return GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0)
end
GEO_DISPLAY_LIST = wrap(0x15)
GEO_SHADOW = wrap(0x16)
GEO_RENDER_OBJ = wrap(0x17)
GEO_ASM = wrap(0x18)
GEO_BACKGROUND = wrap(0x19)
GEO_BACKGROUND_COLOR = GEO_BACKGROUND
GEO_NOP_1A = wrap(0x1A)
GEO_COPY_VIEW = wrap(0x1B)
GEO_HELD_OBJECT = wrap(0x1C)
GEO_SCALE = wrap(0x1D)
GEO_SCALE_WITH_DL = GEO_SCALE
GEO_NOP_1E = wrap(0x1E)
GEO_NOP_1F = wrap(0x1F)
GEO_CULLING_RADIUS = wrap(0x20)
